### ISSUE TITLE
Problems installing Carma

### ISSUE THREAD

**Issue by Bonder-MJ** [ZikunY/CARMA#11]
Hello,

I'm trying to install Carma but I'm getting an issue related to "dsyevd_" from lapack.

installing to /usr/local/lib/R/site-library/00LOCK-CARMA/00new/CARMA/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘CARMA’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/00LOCK-CARMA/00new/CARMA/libs/CARMA.so':
  /usr/local/lib/R/site-library/00LOCK-CARMA/00new/CARMA/libs/CARMA.so: undefined symbol: dsyevd_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/CARMA’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpweksZ5/file42122046e36/CARMA_1.0.tar.gz’ had non-zero exit status
  
I'm trying to install in under R 4.3.1 on linux (Debian GNU/Linux 11 (bullseye))

Best,
Marc

**Comment by ZikunY** [comment]
Hi Marc, 

 This is most likely due to a lack of Intel MLK library, or the system can not find the Intel MLK library. One solution is to install MLK via Conda and then change BLAS/LAPACK using LD_PRELOAD when starting R, such as

 conda install -c anaconda mkl 
LD_PRELOAD=pathto/anaconda3/lib/libmkl_rt.so R

or if MKL is already installed, you can indicate the path to mkl by
 
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmkl_rt.so

The exact path might depend on your system. 

Best,
Zikun

**Comment by Bonder-MJ** [comment]
Hi Zikun,

Thanks for your fast reply. I was having some issues getting a container with this all installed, but I managed now. It might be good to put explicity that you need intel MKL?

Thanks,
Marc

**Comment by ZikunY** [comment]
Hi Marc, 

 I agree, I should make it more explicitly, thanks for reminding. 

Best,
Zikun
