### ISSUE TITLE
Specifications LD matrix

### ISSUE THREAD

**Issue by igarcia17** [ZikunY/CARMA#16]
Dear Dr. Yan
I am deeply interested in your tool, I think it is a very complete and innovative approach and is definetly going to help our research. However, I have some questions regarding the LD matrix construction. Which version of PLINK have you used wth the command
"./plink --bfile bed.file --a1-allele SNP.txt 2 1 '#' --r --matrix --out LD"? 
I am using plink/1.90 and the 'matrix' argument is not recognised, either the 'a1-allele'. Would the command "plink --bfile g1000_eur --extract onlySNP.txt --remove finish.txt --r --out LD_CARMA", being 'onlySNP.txt' a list of the SNPS on the GWAS, be an equivalent solution? I am also confused about what are you trying to do with it, as in some places it seems that you are using the R statistic while in others the Pearson correlation is recommended.
Thank you very much in advance.
Kind regards,
Ines

**Comment by ZikunY** [comment]
Hi Ines, 

 The command line, "./plink --bfile bed.file --a1-allele SNP.txt 2 1 '#' --r --matrix --out LD", means plink 1.9 version. As for the  question, "'#'" might not be necessary. 

 Thanks for the feedback on different routes of getting LD matrix. Presumably, loading the genotype matrix then computing the Pearson correlation in R is recommended here. The plink command here just provides an alternative route for computing the LD. As for the part "--a1-allele SNP.txt", this is due to the fact that sometimes, the allele orders stored in the summary statistics are not consistent to the allele orders recorded in the LD matrix, especially when using external LD. If you are using the in-sample LD, i.e. the LD computed based on the original genotype matrix that were also used in the GWAS, then you could ignore this option. 

Thanks for the feedback. Please let me know if there is any unclear. 

Best,
Zikun

**Comment by igarcia17** [comment]
Dear Dr. Yan

Thank you very much for your fast response, it really helps. I have been using plink 1.90 as well, but I get a Warning message because of the --matrix flag: _Note: --matrix flag deprecated.  Migrate to "--distance ibs flat-missing",
"--r2 square", etc._

Another issue that I encounter is that the LD matrixes generated are gigantic. For instance, I tried to get the LD matrix for 11946 SNPs and it took more than 16TB of storage. This is not pragmatic with my current computational resources. What maximum of SNPs do you recommend?

I'll still be working on these problems because I find your tool deeply useful for my research, Thank you again for your approachability.

Kind regards
Inés

**Comment by ZikunY** [comment]
Hi Ines,

 Great. I think the issue of the warning messages are related to the version of plink. I guess it would be easier just ask chatgpt to have a script of plink for computing the LD matrix with everything here in mind. 

For the size of LD matrix, the rule of thumb is to restrict the fine-mapping method within 1M basepair range. That being said, suppose that there is an index SNP with the smallest p-value to define the risk locus, then the fine-mapping analysis should include all SNPs of +/- 500K basepair range of the index SNP. Depending on data, the number of SNPs included for one locus ranges from 1000 to 4000. 

Many thanks for taking interest in CARMA. :)

Best,
Zikun

**Comment by ZikunY** [comment]
Great to hear it worked out, and had your results. Please let me know if there is any trouble with the annotations. 

Best,
Zikun
