### ISSUE TITLE
Not able to get the same result as the CARMA tutorial

### ISSUE THREAD

**Issue by BideZ** [ZikunY/CARMA#8]
Dear Zikun,

Good day. I have been trying to use a GWAS dataset obtained from GWAS catalog (GCST007236) for calculating the PIPs and identifying candidate causal variants. 
We have used either pre-computed LD (from UKBB), or generated the LD matrix, with plink, based on external reference panels such as 1000G or simulated genotypes utilizing sim1000G. Beside that, we have been experimenting on calculating PIPs and CSs with (everything from the UKB annotations except the polyfun prior) and without functional annotations. 
Unfortuntately, everthing ended up being eliminated when I turned on the outlier for the repetitions where we used the LD matrices generated from 1000G or simulated genotype with sim1000G pack. 
Luckily, despite many SNPs were considered as outliers, we indeed got two credible models when using pre-computed LD from UKBB. But we failed to identify the SNPs documented in the tutorial. None of the credible models matches the ones given in the CARMA tutorial for CR1 gene.
Does anything comes into your mind which might be leading to this? Or is there anything that I have missed.

Thanks!
Best,
Bide

**Comment by ZikunY** [comment]
Hi Bide, 

 Thank you for taking interests in CARMA. One thing I can point out is that the LD matrix that would be eventually used in any fine-mapping methods (including Susie), should not be computed by plink. For some unknown reasons, plink returns LD matrix that is not consistent with the genotypes in the vcf/bed file. I also experienced these problems with plink when using Susie. The proper way would be loading the genotype matrix in R, then compute the LD matrix. 

In the tutorial, the Z scores and LD are provided, did you run CARMA with the Z scores and LD provided through the link in the tutorial? 

Best,
Zikun

**Comment by BideZ** [comment]
Hi Zikun, Thanks for the reply. Wrong GWAS dataset was used and caused the unmatching result. Now I get a similar result in the credible set while the credible models are quite different. But I am happy that I finally got it working :)

Having mentioned the problems caused by LD matrix calculation using plink, would you then suggest any other method that one can take use of for generating LD matrix? We want to calculate it based on 1000 genome project for our own purposes. The LD calculators from Ensembl does not work for snps distant than 500kb. (e.g. the ADAMTS4 gene from the sample dataset ranges from 160656603 to 161655342 position-wise, which is  ~ 1mio bps)

Many thanks in advance!

Best,
Bide

**Comment by ZikunY** [comment]
Hi Bide, 

 I am glad to hear it working now, cheers! 

 As for the computation of LD matrix, I usually loaded the genotype matrix into R and compute the LD matrix by cor() function in R (there are packages for loading plink file into R). CARMA is developed and performed in R environment, so it is most natural and reliable to me. However, before using cor(), it would be good to filter out SNPs by MAF to avoid NA entries generated by cor(). 

Glad I can help. ;). 

Best,
Zikun

**Comment by BideZ** [comment]
Thanks a lot for the suggestions! We have now used two extra approaches for calculating LD matrix for CR1 gene, the illustrated gene in the tutorial. The first method was the cor() in R as mentioned in your previous response. Secondly , we have also used the LD matrices generated by snpStats which yield similar LD values as those from Ensembl. Both trials used 1000G as reference genotype and included the polyfun prior and other functional annotations. However, we failed to get the causal snps mentioned in the tutorial (0 CS and Credible models for snpStats, and completely different results for cor() in R). It seems only strictly following the tutorial using pre-computed Ld matrix from UKBB has worked (as mentioned in my previous posts.). 

Sorry that I have to ask this again, but do you have an idea why this is happening and what would be your suggestions?

Thank you very much in advance!

Best,
Bide

**Comment by ZikunY** [comment]
Hi Bide, 

 Glad that I could help. First, because I never used snpStats before, it would be better that I stay out of commenting on this part. 

 I think it makes sense that it didn't reproduce the results here, primarily due to the usage of 1000G. The summary statistics of CR1 is a meta-analysis of four different cohorts, which includes a cohort of Finland that is known to be different than European descent genetically. Also, out of the four cohorts, only one cohort comes from UKBB, so what we did in the CARMA paper by using UKBB only is already quite borderline. Therefore, using 1000G that has no overlapping to the summary statistics completely creates even further heterogeneity between LD and Z. 

I think there are several things you could do to improve the results. One thing is to adjust the threshold of Bayes factor, i.e. "outlier.BF.index=1/3.2" here, to account for the extra heterogeneity. Another thing is to tune the overall number of iteration of EM algorithm, to prevent overfitting the annotations. See if the results can be improved. 

Best,
Zikun
